
modLoader = "javafml"

loaderVersion = "[47,)"

license = "MIT"

[[mods]]

modId = "modelle"

version = "1.0.0" 

displayName = "Modelle" 





logoFile="logo.png" 



authors = "Lammal220" 






displayTest="MATCH_VERSION" 


description = '''
Modelle allows you to load custom OBJ models with textures directly into your Minecraft world.
Place a Model Block, paste a hash or folder name, and see your model rendered in-game.
Supports rotation, scaling, offset, and server-side model synchronization.
'''

[[dependencies.modelle]] 

modId = "forge" 

mandatory = true 

versionRange = "[47.1.0,)" 



ordering = "NONE"

side = "BOTH"

[[dependencies.modelle]]
modId = "minecraft"
mandatory = true

versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"